while 문을 이용하여 아래 내용을 구현하시오

-손실(loss)가 2.0에서 시작해 매 epoch마다 0.8배로 줄어듭니다


-손실이 0.5 이하가 되려면 몇 epoch가 걸리는지 while 문으로 구하고, 그 때의 손실도 출력하세요

In [ ]:
loss = 2.0
epoch = 0

while loss > 0.5:
    loss = loss * 0.8
    epoch += 1
print("걸린 epoch : ", epoch)
print("걸린 최종 loss : ", loss)

걸린 epoch :  7
걸린 최종 loss :  0.4194304000000002 4


리스트를 받아 가장 작은 값은 0, 가장 큰 값은 1이 되도록 바꿔주는 함수 normalize를 만드세요

(numpy X이고 순수 파이썬으로 작성) (hint) 공식은 (v-최소값)/(최대값 - 최솟값), 최소최대는 min(), max()임




In [ ]:
data = [10,20,30,40,50]

def normalize(data):
    min_val = min(data)
    max_val = max(data)
    return [(v - min_val) / (max_val - min_val) for v in data]

print(normalize(data))
print(normalize([3,1,4,1,5]))


[0.0, 0.25, 0.5, 0.75, 1.0]
[0.5, 0.0, 0.75, 0.0, 1.0]


딕셔너리 모델이 내놓은 예측이름들을 세어서, 많이 나온 순서대로 출력하세요





In [ ]:
pred = ["dog", "cat", "dog", "bird", "dog", "cat"]

count = {}
for p in pred:
  count[p] = count.get(p,0) +1

ranked = sorted(count.items(), key=lambda kv: kv[1], reverse=True)

print(count)
print(ranked)

{'dog': 3, 'cat': 2, 'bird': 1}
[('dog', 3), ('cat', 2), ('bird', 1)]


정답과 예측을 비교해 틀린 위치를 모두 찾고 틀린 개수를 출력하시오

In [ ]:
y_true = [0,1,1,0,1,0,1,1]
y_pred = [0,1,0,0,0,0,1,1]

wrong = []

for i, (t,p) in enumerate(zip(y_true, y_pred)):
  if t != p:
    wrong.append(i)

print(wrong)
print(len(wrong))
print((len(y_true) - len(wrong)/len(y_true)))


[2, 4]
2
7.75


이중 for문


- 2차원 리스트에서각 행의 합과 전체합을 이중 반복문으로 구하기


In [ ]:
matrix = [[1,2,3],[4,5,6],[7,8,9]]

row_sum = []
total_sum = 0

for row in matrix:
  row_sum.append(sum(row))
  total_sum += sum(row)

print("행별 합:", row_sum)
print("전체합 :", total_sum)

행별 합: [6, 15, 24]
전체합 : 45


예상출력

행별 합: [6,15,24]
전체합 : 45

2주차 시작


In [ ]:
import numpy as np
x = np.arange(24).reshape(2,3,4)
print("원래모양 : ",x.shape)
a=x.reshape(2,12)
b=x.reshape(24)
c=x.reshape(6,4)

print(a.shape)
print(b.shape)
print(c.shape)

원래모양 :  (2, 3, 4)
(2, 12)
(24,)
(6, 4)


In [ ]:
import numpy as np

x = np.arange(24).reshape(2,3,4)
print(x)
print(x.sum(axis=0))
print(x.sum(axis=1))
print(x.sum(axis=2))
print(x.sum())

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]
[[12 15 18 21]
 [48 51 54 57]]
[[ 6 22 38]
 [54 70 86]]
276


In [ ]:
x =  np.arange(12).reshape(3,4)
col_vals = np.array([10,20,30,40])
row_vals = np.array([1,2,3])

a = x + col_vals
b = x + row_vals.reshape(3,1)
print(a)
print(b)



[[10 21 32 43]
 [14 25 36 47]
 [18 29 40 51]]
[[ 1  2  3  4]
 [ 6  7  8  9]
 [11 12 13 14]]


In [ ]:
data = np.array([[2.0,10.0],[4.0,20.0],[6.0,30.0],[8.0,40.0]])

lo = data.min(axis=0)
hi = data.max(axis=0)
scaled = (data-lo)/(hi-lo)

print("lo: ",lo)
print("hi: ",hi)
print(scaled.round(4))


lo:  [ 2. 10.]
hi:  [ 8. 40.]
[[0.     0.    ]
 [0.3333 0.3333]
 [0.6667 0.6667]
 [1.     1.    ]]


표 만들고 살펴보기
- 센서 로그 에제 df를 만들고 모양, 열이름 각열의 자료형 출력하기
- 요약 통계도 출력하기
- 예양 출력
모양 : (6,4)
열 이름: ['센서ID', '온도','습도', '정상']
센서ID str
온도 float
습도 int64
정상 int64
dtype: object


In [ ]:
import pandas as pd
log = {
    "센서ID": ["S1","S2", "S3", "S4", "S5"],
    "온도" : [19.5,22.1,22.5,24.2,29.1],
    "습도" : [67,57,48,62,65],
    "정상" : [1,1,0,1,1]
}
df = pd.DataFrame(log)

print(df)
print(df.shape)
print(df.columns)
print(df.dtypes)
print(df.describe())

  센서ID    온도  습도  정상
0   S1  19.5  67   1
1   S2  22.1  57   1
2   S3  22.5  48   0
3   S4  24.2  62   1
4   S5  29.1  65   1
(5, 4)
Index(['센서ID', '온도', '습도', '정상'], dtype='object')
센서ID     object
온도      float64
습도        int64
정상        int64
dtype: object
              온도         습도        정상
count   5.000000   5.000000  5.000000
mean   23.480000  59.800000  0.800000
std     3.563987   7.596052  0.447214
min    19.500000  48.000000  0.000000
25%    22.100000  57.000000  1.000000
50%    22.500000  62.000000  1.000000
75%    24.200000  65.000000  1.000000
max    29.100000  67.000000  1.000000


조거 두 개 결합하기
- 위에서 온도가 20이상이면서 습도가 60미만인 행 골라내기
- 명 챙이 남았는지 출력하기
- [코드시작]
  c1 코드와 동일
- [예상 출력]
  센서id 온도 습도 정상
  0 S1 21.5 55 1
  1 S1 22.1 57 1
  2 S2 22.5 48 0
  3 S3 24.8 62 1
  4 S4 19.2 65 .

In [ ]:
sel = (df['온도'] >= 20) & (df['습도'] < 60)
print(df[sel])
print(len(df[sel]))

  센서ID    온도  습도  정상
1   S2  22.1  57   1
2   S3  22.5  48   0
2


정렬하고 상위 N개 뽑기 (sort_values)


In [ ]:
top3 = df.sort_values("온도", ascending = False).head(3)
print(top3)

  센서ID    온도  습도  정상
4   S5  29.1  65   1
3   S4  24.2  62   1
2   S3  22.5  48   0


In [ ]:
print(df.isna().sum)
df["온도"].fillna(df["온도"].mean())

X = df[["온도", "습도"]].values
y = df["정상"].values


print(df)
print(X.shape)
print(y)

<bound method DataFrame.sum of     센서ID     온도     습도     정상
0  False  False  False  False
1  False  False  False  False
2  False  False  False  False
3  False  False  False  False
4  False  False  False  False>
  센서ID    온도  습도  정상
0   S1  19.5  67   1
1   S2  22.1  57   1
2   S3  22.5  48   0
3   S4  24.2  62   1
4   S5  29.1  65   1
(5, 2)
[1 1 0 1 1]
